{
	"data": "ENC[AES256_GCM,data:WCMlpDkuNnCiDaFlQr2Hgl5EkqG52zRLXLSh+pTAOIJasgveDbmzbOSog/aPKM64bVGTlJquOnedvLbAPM2giSHr+1DxcPtTNKfNM78Y5EVm8zg6P9/I5JlHuINK/agHkUc/DALQUs8+NbODFh6y,iv:r/5iVgfZRLea6KVt8vocCo+QbqzYeAx01R0I221fQpg=,tag:xUyxMoYKkakC2xnsU5QRkA==,type:str]",
	"sops": {
		"kms": null,
		"gcp_kms": null,
		"lastmodified": "2019-10-14T14:27:13Z",
		"mac": "ENC[AES256_GCM,data:bt4B1NVK2D/LmheCo2pZdrdrI1qgug3yNufSSpXfQdD/ZjPS7pBxkkyIJHe14WAQUOmXW400sahrhjnqcHIBCngGDWVukxGPsFCtthaGygRKvDkL7UUNlMKvtO6YOw1EHAsaFD0Ygml3WjqkaE0ToHHf92ibGOQwx5TYOH2jHXQ=,iv:UP0CA415pEVXS0Ms1+szI6jotPjeemoAXxaDyTF/o8M=,tag:9POcd9INNIu1n+RFhoq0cA==,type:str]",
		"pgp": [
			{
				"created_at": "2019-07-17T21:51:34Z",
				"enc": "-----BEGIN PGP MESSAGE-----\n\nhQEMA+3cycjXyJdVAQf9HukbvHgRPxXqjEDlcv1cTVd6XU2RTcAUei7aWetprzX8\nWRTFsSZku7H8+LfppN2cOnckSPh5KJE6pmEY/oyUCiYjgCmKjwiGsN2zBZ/3Qlvv\n9yj1YK45gZ2yGFmhCp4GP8gEF9uOrYoxGMS8n9bW53XKOMWoCJ7R3Amhq6+jLNYF\nm/rTI5BROSvpgWWKdEfQungjkqgBpnd26m2xR3576mfM66ry9KBu3NIha0C3DJHZ\nBxnX5HyLq7kWbMk76dXQIRNJC/9vNxBs4ow4q/V8Sibj29+MpBPZCPskxxHEDX/7\nqNpHs0dQLO4sfilOWs5OsIZ9N7gYrcNoTBWJ9BZCf9JeAYQBTurKF5gktgF8wqOd\ngTNnW3ufonJ7kkTOnau3XfIH3bQNbvFKjFk7vY86cNFdvKCViPGn+RuyphSMz+Zg\nPMVOSZ0AAhRcCM6yPpbfguJsj21EBul1Pze2g0S8+Q==\n=U1nK\n-----END PGP MESSAGE-----\n",
				"fp": "E14104A0890994B9AC9C9F6782C1FF5E679EFF32"
			}
		],
		"unencrypted_suffix": "_unencrypted",
		"version": "3.0.5"
	}
}